### ISSUE TITLE
Teammate Quiz Game with GUI

### ISSUE THREAD

**Issue by titaniumtushar** [Tech-Bizz-Devs/OH24-CPP-Java#3]
**Task Description:**
- [ ] Design and implement a simple quiz game to help your teammates get to know each other in OpenHack. 
- [ ] Setup a scorecard to see who scored highest. (Without database)
- [ ] The quiz game will consist of questions based on the participating teammates, allowing users to learn more about each other in a fun and interactive way. 
- [ ] The application should feature a graphical user interface (GUI) for a seamless user experience and should be easy to use for participants with varying levels of technical expertise.
