### ISSUE TITLE
Typing Speed Test GUI

### ISSUE THREAD

**Issue by titaniumtushar** [Tech-Bizz-Devs/OH24-CPP-Java#5]
**Task Description:**

- [ ] Design and implement a typing speed test application with a graphical user interface (GUI) in either Java or C++. 
- [ ] The application will allow users to take a typing speed test by typing a given text passage within a specified time limit. 
- [ ] Upon completion, the application will calculate the user's typing speed (in words per minute) and display the result.
- [ ]  Additionally, users can compare their scores with previous attempts to track their typing progress.(optional)

Use of Database is optional.
